// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "v_video_compressor",
    platforms: [
        .iOS("13.0")
    ],
    products: [
        .library(name: "v-video-compressor", targets: ["v_video_compressor"])
    ],
    dependencies: [
        // Generated by the Flutter tool (3.38+) next to this package at build time.
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: [
        .target(
            name: "v_video_compressor",
            dependencies: [
                .product(name: "FlutterFramework", package: "FlutterFramework")
            ],
            resources: [
                .process("PrivacyInfo.xcprivacy")
            ]
        )
    ]
)
